src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether or not this account is active for Quickbooks billing purposes.</description>
        <inlineHelpText>Indicates whether or not this account is active for Quickbooks billing purposes.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JSA_State__c</fullName>
        <description>Two character abbreviation of the JSA State (based on the Zone, which is based on ZIP code).</description>
        <formula>LEFT( Zone__c , 2)</formula>
        <inlineHelpText>Two character abbreviation of the JSA State (based on the Zone, which is based on ZIP code).</inlineHelpText>
        <label>JSA State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Six character (including dash) field that indicates JSA State and sub-jurisdiction of the school.</description>
        <inlineHelpText>Six character (including dash) field that indicates JSA State and sub-jurisdiction of the school.</inlineHelpText>
        <label>Zone</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_State__c</fullName>
        <formula>High_School__r.JSA_State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The two character abbreviation for the JSA state, based on the location of the associated High School for the contact.</inlineHelpText>
        <label>JSA State</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Conventions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>a list of conventions open for registration</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JSA_State__c</fullName>
        <label>JSA State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Close_Date__c</fullName>
        <label>Registration Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>open_date__c</fullName>
        <label>open date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Conventions</label>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Schools</relationshipLabel>
        <relationshipName>R00N40000001qFBVEA2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JSA_State__c</fullName>
        <formula>Account__r.JSA_State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JSA State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <formula>Account__r.Zone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>JSA Zone, from the Account for the High School.</inlineHelpText>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HotelRoom__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>HR-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>JSA_State__c</fullName>
        <formula>Primary_Contact__r.JSA_State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>JSA State abbreviation, based on JSA State from Primary Contact Link.</inlineHelpText>
        <label>JSA State</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/state_region_mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>region_name__c</fullName>
        <label>region name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>state to region mapping</label>
</CustomObject>

src/objects/Zone_Pricebook_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>pricebookId__c</fullName>
        <description>the ID of the mapped pricebook: IDs</description>
        <label>Pricebook Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zone Pricebook Mapping</label>
</CustomObject>

src/classes/testUtils.cls
public with sharing class testUtils 
{
	public static User sysadmin 	
	{
		get
		{
			if(sysadmin == null)
			{
				sysadmin = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
			}
			
			return sysadmin;
		}
		set;
	}
	
	public static User createPortalUser(string uname,Id contactId)
	{
		User u = new User();
		Id profileId = [SELECT Id FROM Profile WHERE Name = 'Event Registration Portal User'].id;
		
		u.Username = System.currentTimeMillis() + uname;
		u.alias = 'port'; 
    	u.email = System.currentTimeMillis() + uname;
        u.emailencodingkey = 'UTF-8'; 
        u.lastname = 'nothingmuch';
        u.languagelocalekey = 'en_US'; 
        u.localesidkey = 'en_US';
        u.profileid = profileId; 
        u.contactId = contactId;
        u.timezonesidkey = 'America/Los_Angeles';
		
		return u;
	}

	public static list<opportunity> createOpportunities(integer size,string name,string stagename,date closedate)
	{
		List<Opportunity> opps = new List<Opportunity>();
		
		for(integer i=0;i<size;++i)
		{
			Opportunity opp = new Opportunity();
			opp.name = name;
			opp.stagename=  stagename;
			opp.closeDate= closeDate;
			opps.add(opp);
		}
		
		return opps;
	}
	
	public static list<Account> createAccounts(integer size,string Name, string Zone)
	{
		List<Account> accs = new List<Account>();
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
		UserRole role =  [select Id from UserRole where name = 'Campus Director' limit 1];
		User u = [select Id from user where userRoleId != null limit 1];
		
		for(integer i=0;i<size;++i)
		{
			Account acc = new Account();
			acc.name = name;
			acc.OwnerId = u.id;
			acc.Zone__c = zone;
			accs.add(acc);
		}
		
		return accs;
	}
	
	
	public static list<Contact> createContacts(integer size,string LastName,Id accId)
	{
		List<Contact> cs = new List<Contact>();
		
		for(integer i=0;i<size;++i)
		{
			Contact c = new Contact();
			c.LastName = LastName;
			c.AccountId = accId;
			cs.add(c);
		}
		
		return cs;
	}
	
	public static list<Conventions__c> createConventions(List<date> startDates,string conType)
	{
		list<Conventions__c> cons = new List<Conventions__c>();
		
		for(Date startDate : startDates)
		{
			Conventions__c con = new Conventions__c();
			con.name = 'convention at ' + startDate.format();
			con.active__c = true;
			con.open_date__c = startDate;
			con.Type__c = conType;
			con.Start_Date__c = startDate;
			con.End_Date__c = startDate +5;
			con.Registration_Close_Date__c = startDate - 1;
			con.JSA_State__c = 'NC';
			cons.add(con); 
		}
		
		return cons;
	}
	
	public static list<Zone_Pricebook_Mapping__c> createZoneMappings(map<string,string> zoneToPbid)
	{
		list<Zone_Pricebook_Mapping__c> maps = new list<Zone_Pricebook_Mapping__c>();
		
		for(string zone : zoneToPbid.keySet())
		{
			Zone_Pricebook_Mapping__c mapping = new Zone_Pricebook_Mapping__c();
			mapping.Name = zone;
			mapping.pricebookId__c = zoneToPbid.get(zone);
			
			maps.add(mapping);
		}
		
		return maps;
	}
	
	public static list<PricebookEntry> createPricebookEntries(list<Product2> products,Id priceBookId)
	{	
		list<PricebookEntry> pbes = new list<PricebookEntry>();
		
		for(Product2 prod : products)
		{
			PricebookEntry pbe = new PricebookEntry();
			pbe.Product2Id = prod.id;
			pbe.Pricebook2Id = priceBookId;
			pbe.UnitPrice = 1;
			pbe.IsActive = true;
			pbe.UseStandardPrice = false;

			pbes.add(pbe);
		}
		
		return pbes;
	}
	
	public static Product2 createProduct(string Name)
	{
		Product2 prod = new Product2();
		prod.name = Name;
		prod.IsActive = true;
		return prod;
	}
	
	public static High_School__c createHighSchool(String Name, Account acc )
	{
		High_School__c hs = new High_School__c();
		hs.name = Name;
		hs.Account__c = acc.id;
		return hs;
	}
	
	public static list<Application__c> createApplications(integer size,Opportunity opp, Contact con,Product2 prod)
	{
		list<Application__c> apps = new list<Application__c>();
		for(integer i=0;i<size;++i)
		{
			Application__c app = new Application__c();
			app.Contact__c = con.id;
			app.Opportunity__c = opp.id;
			app.Product2__c = prod.id;
			apps.add(app);
		}
		
		return apps;
	}
	
	public static state_region_mapping__c createStateRegionMapping(string name,string regionName)
	{
		state_region_mapping__c mapping = new state_region_mapping__c(name=name,region_name__c = regionName);
		return mapping;
	}
	
	public static List<HotelRoom__c> createHotelRooms(integer size,Opportunity op)
	{
		List<HotelRoom__c> rooms = new List<HotelRoom__c>();
		
		for(integer i=0;i<size;++i)
		{
			HotelRoom__c rm = new HotelRoom__c();
			rm.Opportunity__c = op.id;
			rooms.add(rm);
		}
		
		return rooms;
	} 
}