src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Countries__c</fullName>
        <label>Countries</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>US_States__c</fullName>
        <label>US States</label>
        <picklist>
            <controllingField>Countries__c</controllingField>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>HighSchool</fullName>
        <active>true</active>
        <description>Use this record type for High Schools (including chapters) (Grades 9-12 or 10-12)</description>
        <label>High School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Are you a student, teacher or chaperon?</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Alum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS Educator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>High_School_Graduation_Year__c</fullName>
        <label>High School Graduation Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>High_School_Text__c</fullName>
        <label>High School (Text)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_Role__c</fullName>
        <inlineHelpText>JSA Advisor = Designated Teacher/Advisor
JSA Affiliate = Other Chaperone</inlineHelpText>
        <label>JSA Role</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Affairs Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Interested Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Guardian_First_Name__c</fullName>
        <inlineHelpText>Please enter the first name of your parent of legal guardian.  We require this information from any program participant under 18 years of age.</inlineHelpText>
        <label>Parent/Guardian First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Guardian_Last_Name__c</fullName>
        <inlineHelpText>Please enter the last name of your parent of legal guardian.  We require this information from any program participant under 18 years of age.</inlineHelpText>
        <label>Parent/Guardian Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_or_Guardian_s_Email__c</fullName>
        <inlineHelpText>Provide one email address for a parent or legal guardian.</inlineHelpText>
        <label>Parent or Guardian&apos;s Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account__r.BillingState</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/myJSAprofileController.cls
global with sharing class myJSAprofileController {

	public Contact contact {get; set;}
	public String highSchoolState {get; set;}
	public String highSchoolName {get; set;}
	public Boolean showEvents {get;set;}

	public void initPage() {
		Id contactId = [select ContactId from User where Id = :UserInfo.getUserId()].ContactId;
		contact = [select FirstName, LastName, MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry,
						  Account.BillingCountry, Account.BillingState, Account.Countries__c, Account.US_States__c, AccountId,
		                  MobilePhone, Phone, Gender__c, High_School_Graduation_Year__c, Birthdate, Parent_Guardian_First_Name__c,
		                  Parent_Guardian_Last_Name__c, Parent_or_Guardian_s_Email__c, High_School__c , Category__c, JSA_Role__c, High_School_Text__c
		           from Contact
		           where Id = :contactId];
		
		showEvents = portalServices.showEvents();
		
		if (contact.High_School__c != null) {
			High_School__c hs = [select Name, State__c from High_School__c where Id = :contact.High_School__c];
			highSchoolState = hs.State__c;
			highSchoolName = hs.Name;
			contact.High_School_Text__c = highSchoolName;
		}
		
	}
	
	public void save() {
		Account updatedAccount = new Account(Id=contact.AccountId);
		updatedAccount.Countries__c = contact.Account.Countries__c;
		updatedAccount.US_States__c = contact.Account.US_States__c;
		updatedAccount.BillingCountry = contact.Account.Countries__c;
		updatedAccount.BillingState = contact.Account.US_States__c;
		contact.MailingCountry = contact.Account.Countries__c;
		contact.MailingState = contact.Account.US_States__c;
		update updatedAccount;
		update contact;
	}

	
	
	public List<SelectOption> genderOptions {
		get {
			if (genderOptions == null) {
				genderOptions = new List<SelectOption>();
				genderOptions.add(new SelectOption('Female', 'Female'));
				genderOptions.add(new SelectOption('Male', 'Male'));
			}
			
			return genderOptions;
		}
		
		private set;
	}
	
	
	
	public List<SelectOption> highSchoolStateOptions {
		get {
			if (highSchoolStateOptions == null) {
				highSchoolStateOptions = new List<SelectOption>();
				
				Set<String> states = new Set<String>();
				
				for (High_School__c highSchool : [select State__c from High_School__c where State__c != null]) {
					states.add(highSchool.State__c);
				}
				
				List<String> stateList = new List<String>();
				stateList.addAll(states);
				stateList.sort();
				
				for (String state : stateList) {
					highSchoolStateOptions.add(new SelectOption(state, state));
				}
			}

			return highSchoolStateOptions;
		}
		
		private set;
	}
	
	@remoteAction
	global static List<Map<String,String>> findSchools(String searchTerm, String highSchoolState){
		//send back the json that jquery autocomplete expects
		List<Map<String,String>> schools = new  List<Map<String,String>> {};
		//wrap the search term in wildcard characters for most flexible search
		searchTerm = '%' + searchTerm + '%';
		//SOQL in a for loop for maximum rows returned
		for(High_School__c school : [select Id, Name from High_School__c where Name like : searchTerm and State__c =: highSchoolState order by Name]){
			//using literal syntax to add anonymous maps to the list
			schools.add(new Map<String,String>{'label' => school.Name, 'value' => school.Id});
		}
		//list of maps turns to JSON by itself with JSR
		return schools;
	}

}