src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>HighSchool</fullName>
        <active>true</active>
        <description>Use this record type for High Schools (including chapters) (Grades 9-12 or 10-12)</description>
        <label>High School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Honor_Student_Code__c</fullName>
        <inlineHelpText>The Honor Student code is a 6 character code on the address panel of mailings.  It may also be used in emails.  Note that we have this same field on Opportunities (exposed via the portal), so we may need to merge the two fields for reporting purposes.</inlineHelpText>
        <label>Honor Student Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Use this record type for current high school students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academics_Complete__c</fullName>
        <formula>IF (AND (Current_Secondary_School__c&lt;&gt;&quot;&quot;, Reference_Teacher_Name__c&lt;&gt;&quot;&quot;, Reference_Teacher_Email__c&lt;&gt;&quot;&quot;),&quot;True&quot;, &quot;False&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Please complete all fields under the Academics tab above. After all information has been filled in and verified, this step will be shown as complete.</inlineHelpText>
        <label>Academics Section Complete?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campus_Session__c</fullName>
        <inlineHelpText>Please select your first choice campus and session.</inlineHelpText>
        <label>Campus/Session</label>
        <picklist>
            <picklistValues>
                <fullName>JSA Diplomat Program, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Princeton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at University of Virginia (APUSH)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Stanford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Georgetown - Session II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Georgetown - Session I</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extracurricular_Activities__c</fullName>
        <description>Please see the Application Instructions under the Quick Links menu. We recommend that you write and check your essay using a word processing program, then paste the entire essay here.  When you are satisfied with your essays, click &quot;Submit&quot; and &quot;Update.&quot;</description>
        <inlineHelpText>Please see the Application Instructions under the Quick Links menu. We recommend that you write and check your essay using a word processing program, then paste the entire essay here.  When you are satisfied with your essays, click &quot;Submit&quot; and &quot;Update.&quot;</inlineHelpText>
        <label>Extracurricular Activities</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Honor_Student_Code__c</fullName>
        <description>Mailing list code.</description>
        <inlineHelpText>If there is an Honor Student Code near the address box on the brochure or mailing that you received, please enter it here.</inlineHelpText>
        <label>Honor Student Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Essay_Status__c</fullName>
        <inlineHelpText>Paste your completed essays into the fields under the Essay tab above. After both answers have been submitted and reviewed, this step will be shown as &quot;Received.&quot;</inlineHelpText>
        <label>Essay Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Personal_Essay__c</fullName>
        <description>Please write an essay of at least 250 words, but no more than 750 words, on one of the topics below. The personal essay helps us understand you as a person and a student, aside from your grades. It also demonstrates your ability to organize your thoughts and express yourself (plus, it&apos;s great preparation for the Common Application for college).</description>
        <label>Personal Essay</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference_Teacher_Email__c</fullName>
        <inlineHelpText>Enter the email address for the teacher or counselor who will provide a recommendation letter.</inlineHelpText>
        <label>Reference Teacher Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Reference_Teacher_Name__c</fullName>
        <inlineHelpText>Enter the first and last name of the teacher whom you will ask to provide a recommendation letter.  DO NOT enter any salutation, such as &quot;Mr.&quot;, &quot;Mrs.&quot;, or &quot;Dr.&quot;</inlineHelpText>
        <label>Reference Teacher Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Choice__c</fullName>
        <inlineHelpText>Please enter your second choice campus/session.  If we cannot accept you into your first choice we will consider your application for your second choice.</inlineHelpText>
        <label>Second Choice Session</label>
        <picklist>
            <controllingField>Campus_Session__c</controllingField>
            <picklistValues>
                <fullName>Summer School at Princeton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Stanford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Georgetown - Session I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at Georgetown - Session II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer School at University of Virginia (APUSH)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Teacher_recommendation_letter__c</fullName>
        <inlineHelpText>After you submit the name and email address of the teacher or counselor who will provide your recommendation letter, we will send a request via email. When we receive the recommendation this field will be updated to &quot;Received.&quot;</inlineHelpText>
        <label>Teacher Recommendation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Reply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>symLeadership_Positions__c</fullName>
        <inlineHelpText>List any leadership positions you have held. If you have not held any leadership roles you can list relevant clubs or extracurricular activities. Please limit your answer to 100 words or less.</inlineHelpText>
        <label>Leadership Positions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>symMost_Important_Issue__c</fullName>
        <inlineHelpText>Describe an important issue facing government and your proposed solution. Alternatively, tell us an issue you would like to discuss or debate at the symposium. Please limit your answer to 100 words or less.</inlineHelpText>
        <label>Most Important Issue/Solution</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestJSAApplicationController.cls
@isTest
private class TestJSAApplicationController {

    static User portalUser;
   
    static testMethod void setupandTest() {
  
        
        Test.startTest();
        
        Product2 prod = testUtils.createProduct('testsession');
        prod.ProductCode = 'SSABC';
        insert prod;
             
        List<Opportunity> opps = TestUtils.createOpportunities(1,'testsummeropp','Application Started', system.Today().addDays(14));
        Opportunity opp = opps[0];
        
        opp.RecordTypeId = '012400000005P4d';
        opp.Reference_Teacher_Name__c= 'Tester teacher';
        opp.ExtraCurricular_Activities__c = 'sample extracurricular activities';
        opp.Personal_Essay__c = 'sample personal essay';
        opp.symLeadership_Positions__c = 'sample leadership desc';
        opp.Amount = 500.00;
        opp.symMost_Important_Issue__c = 'sample important issue';
        opp.Campus_Session__c = 'testsession';
        opp.Second_Choice__c = 'testsession';
        opp.Teacher_recommendation_letter__c = 'teststatus';
        //-- Suyati Modified - 25/Nov/2014
        //-- Included Honor Student Code
        opp.Honor_Student_Code__c = 'HSCODE';
        insert opp;  
      
        List<Account> accs = TestUtils.createAccounts(1,'Test Account','PST');
        Account acc = accs[0];
        insert acc;
        List<Contact> contacts = TestUtils.createContacts(1,'test contact', acc.Id);
        Contact con = contacts[0];
        insert con;
        portalUser = testUtils.createPortalUser('appsuperbort@bort.com.bort', con.id);
        system.runAs(testUtils.sysadmin)
        {
            insert portalUser;
        }          
        
        system.runas(portalUser) {
            ApexPages.currentPage().getParameters().put('opId', opp.Id);     
            ApexPages.currentPage().getParameters().put('ApplicationType', 'SS');      
            
            JSAApplicationController c = new JSAApplicationController();
            
            system.assertEquals(c.OpId, opp.Id);
            system.assertEquals('SS', c.ApplicationType);
            system.assertEquals(opp.Id, c.Op.Id);
            system.assertEquals('testsummeropp', c.OpName);
            system.assertEquals(true, c.IsSSApplication);
            system.assertEquals(false, c.IsSympApplication);
            system.assertEquals(opp.Reference_Teacher_Name__c, c.RefTeacherName);
            system.assertEquals(opp.ExtraCurricular_Activities__c, c.ExtraCurricularActivities);
            system.assertEquals(opp.Personal_Essay__c,c.personalEssay);
            system.assertEquals(string.valueof(opp.Amount), c.TotalAmount);
            system.assertNotEquals(null, c.SalesOrderNumber);
            system.assertEquals(opp.symLeadership_Positions__c, c.LeadershipPositions);
            system.assertEquals(opp.symMost_Important_Issue__c, c.MostImportantIssue);
            system.assertEquals(prod.ProductCode, c.SelectedSession);
            system.assertEquals(prod.ProductCode, c.SelectedSecondChoice);
            system.assertEquals(1, c.SSCourses.size());
            
            //-- Suyati Modified - 25/Nov/2014
            //-- Included assertion for Honor Student Code
            system.assertEquals('HSCODE', c.HonorStudentCode);
            
            
            //verify content map keys added to the list
            system.assertEquals(true, c.OverviewContentKeys.contains('Personal Data Complete?'));
            system.assertEquals(true, c.OverviewContentKeys.contains('Recommendation Section Complete?'));
            system.assertEquals(true, c.OverviewContentKeys.contains('Teacher Recommendation Status?'));
            system.assertEquals(true, c.OverviewContentKeys.contains('Transcript Status?'));
            system.assertEquals(true, c.OverviewContentKeys.contains('Essay Status?'));
            system.assertEquals(true, c.OverviewContentKeys.contains('Scholarship Status?'));
            /*system.assertEquals(true, c.OverviewContentKeys.contains('Need scholarship / fundraising packet?'));*/
            system.assertEquals(true, c.OverviewContentKeys.contains('Acceptance Status'));
            
            system.assertEquals( c.contact.Id, con.Id);
            system.assertEquals(c.Submitted, false);
            system.assertEquals(c.OverviewContent.size() > 0, true);
            system.assertEquals(c.op.Academics_Complete__c,c.overviewContent.get('Recommendation Section Complete?'));
            //system.assertEquals('Incomplete',c.overviewContent.get('Personal Data Complete?'));
            system.assertEquals('teststatus', c.overviewContent.get('Teacher Recommendation Status?'));
            system.assertEquals('Requested', c.overviewContent.get('Transcript Status?'));
            system.assertEquals(c.op.Personal_Essay_Status__c, c.overviewContent.get('Essay Status?'));
            system.assertEquals('Not Applicable', c.overviewContent.get('Scholarship Status?'));
            system.assertEquals('false', c.overviewContent.get('Need scholarship / fundraising packet?'));
            system.assertEquals(c.ReferralOptions.size()> 0, true);
            system.assertEquals(true,c.highschoolstateOptions != null);
            system.assertEquals(true, c.SSSessionMap != null );
            system.assertEquals(true, c.SympSessionOptions != null );
            system.assertEquals(true, c.SSSessionOptions != null);
            system.assertEquals(true, c.invoices != null);
            system.assertEquals(c.invoices.size(), c.invoiceNumbers.size());
            system.assertEquals(true,string.isblank(c.highschool));
            system.assertEquals(true, string.isblank(c.highschoolstate));
            system.assertEquals(true, string.isblank(c.highschooltext));
            
            if(c.invoices.size() ==  0) {
                system.assertEquals('N/A', c.oppInvoiceNumber);
            }
            system.assertEquals('testsummeropp', c.opName);
            system.assertEquals(opp.Id, c.OpIdparam);
            system.assertEquals(true, c.op!=null );
            
            string refteacherName = 'test developer';
            c.RefTeacherName = refteacherName;
            c.extracurricularActivities = 'test extra curricular activities';
            c.personalEssay = 'test personal essay';
            c.saveopp();            
                    
            string refteacherEmail = 'test@test.com';
            c.RefTeacherEmail = refteacherEmail ;
            c.submit();
             
           // Opportunity requeriedOpp = [select Id, Reference_Teacher_Email__c,Application_Submitted__c from Opportunity where Id =:opp.Id ];
            //system.assertequals(refteacherEmail, requeriedOpp.Reference_Teacher_Email__c);
            system.assertEquals(true, JSAApplicationController.findSchools('Ala','CA' ) != null );
            //system.assertEquals(true,requeriedOpp.Application_Submitted__c);
            system.assertEquals(false, c.Submitted);
            //system.assertEquals(true, requeriedOpp.Application_Submitted__c);
            
            JSAApplicationController.QBPayment pmt = new JSAApplicationController.QBPayment('111', 'Paypal', system.now(),35.35);
            system.assertEquals('111', pmt.Id);
            system.assertEquals('Paypal', pmt.PaymentMethod);
            system.assertEquals(string.valueof(system.now().date()), pmt.PaymentDate);
            system.assertEquals(35.35, pmt.PaymentAmount);
            
            JSAApplicationController.QBCreditMemoLineItem memoitem = new JSAApplicationController.QBCreditMemoLineItem(system.now(), 'test' , 55.55);
            system.assertEquals(string.ValueOf(system.now().date()),memoitem.CreditMemoNumbersDate);
            system.assertEquals('test', memoitem.LineDescription);
            system.assertEquals(55.55, memoitem.LineAmount);
        }
        Test.stopTest();
        
    }
}