src/objects/Application__c.object
<CustomObject>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Are you a student, teacher or chaperon?</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Alum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS Educator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Use this record type for current high school students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HotelRoom__c.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Room_Type__c</fullName>
        <label>Room Type</label>
        <picklist>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher / Advisor Shared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher / Advisor Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>HR-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <formula>CASE( Primary_Contact__r.Gender__c , &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ocHigh_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>High School Chapter that is sending a delegation (applies only to group opportunities).</inlineHelpText>
        <label>Host Chapter</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Overnight Conventions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zone_Pricebook_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Zone Pricebook Mapping</label>
</CustomObject>

src/classes/myJSAroomSelectionContExtTest.cls
@isTest
public with sharing class myJSAroomSelectionContExtTest
{
	public static Opportunity testOp;
	public static High_School__c testHs;
	
	public static jsaPortalEventController testController;
	public static myJSAroomSelectionContExt testContExt;
	
	static Account hsAccount;
	static High_School__c hs;
	static final string ZONE = 'ZZ';
	static PricebookEntry studentProductEntry;
	static PricebookEntry teacherProductEntry;
	static list<Product2> products;
	static list<Application__c> applications;
	static list<Contact> contacts;
	
	static final integer NUM_APPLICATIONS = 3;
	
	public static void setup(Pricebook2 pb)
	{
		hsAccount = testUtils.createAccounts(1,'hsAcc',ZONE)[0];
		insert hsAccount;
		
		hs = testUtils.createHighSchool('na',hsAccount);
		insert hs;

		list<Zone_Pricebook_Mapping__c> mapping = testUtils.createZoneMappings(new map<string,string>
		{
			ZONE => pb.id
		});
		
		system.runAs(testUtils.sysadmin)
		{
			delete Zone_Pricebook_Mapping__c.getAll().values();
			insert mapping;
		}
		
		products = new list<product2>
		{
			testUtils.createProduct('Teacher Package - test'),
			testUtils.createProduct('Student Package - test'),
			testUtils.createProduct('unrelated')
		};
		
		insert products;
		
		Pricebook2 standardPricebook = [SELECT Id FROM Pricebook2 WHERE isStandard=true];
		
		list<PricebookEntry> stdEntries = TestUtils.createPricebookEntries(products, standardPricebook.id);
		insert stdEntries;
		
		list<PricebookEntry> newEntries = TestUtils.createPricebookEntries(products, pb.id);
		insert newEntries;
		
		studentProductEntry = newEntries[1];
		teacherProductEntry = newEntries[0];
		
		testOp = testUtils.createOpportunities(1, 'testOp', 'I:Intent', Date.today())[0];
		testOp.AccountId = hsAccount.id;
		testOp.ocHigh_School__c = hs.id;
		insert testOp;
		
		contacts = testUtils.createContacts(NUM_APPLICATIONS, 'whocares', hsAccount.id);
		for(contact c : contacts)
		{
			c.High_School__c = hs.id;
			c.Category__c = myJSAroomSelectionContExt.TEACHER_ROLE;
			c.Gender__c = myJSAroomSelectionContExt.FEMALE_GENDER;
		}
		
		insert contacts;
		
		Applications = new List<Application__c>
		{
			testUtils.createApplications( 1, testOp, contacts[0], products[0] )[0],
			testUtils.createApplications( 1, testOp, contacts[1], products[0] )[0],
			testUtils.createApplications( 1, testOp, contacts[2], products[0] )[0]
		};
		
		insert applications;
		
		ApexPages.currentPage().getParameters().put(jsaPortalEventController.ID_PARAM, testOp.id);
		testController = new jsaPortalEventController();
		testContExt = new myJSAroomSelectionContExt(testController);			
	}
	
	@isTest(seeAllData=true)
	public static void testSummaryData()
	{
		pricebook2 pb = new pricebook2();
		pb.Name = 'testPB';
		insert pb;
		
		test.startTest();
			setup(pb);
		test.stopTest();
		
		system.assertEquals(NUM_APPLICATIONS,testContExt.totalDelegates,'the correct number of applicants should be counted');
		system.assertEquals(0,testContExt.appliedFemaleStudents,'no female students should have applied');
		system.assertEquals(0,testContExt.appliedMaleStudents,'no male students should have applied');
		system.assertEquals(0,testContExt.appliedMaleTeachers,'no male teachers should have applied');
		system.assertEquals(NUM_APPLICATIONS,testContExt.appliedFemaleteachers,'the correct number of female teachers should have been found');
		system.assertEquals(0,testContext.assigned,'nobody should be assigned yet');	
	}
	
	@isTest(seeAllData=true)
	public static void testRoomWrappers()
	{
		pricebook2 pb = new pricebook2();
		pb.Name = 'testPB';
		insert pb;
		setup(pb);
		
		List<HotelRoom__c> rooms = testUtils.createHotelRooms(1, testOp);
		rooms[0].Room_Type__c = 'Teacher';
		rooms[0].Gender__c = 'Female';
		insert rooms;
		
		test.startTest();
			testContExt.updateRoomsAndContacts();
		test.stopTest();
		
		system.assertNotEquals(null,testContExt.theRooms,'there should be rooms');
		
		myJSAroomSelectionContExt.roomWrapper room = testContExt.theRooms[0];
		
		system.assertEquals(true,room.readyForDelegates,'the room should be ready for delegates');
		system.assertEquals(false,room.hasDelegates(),'the room should not have any delegates');
		
		room.resetRoom();
		
		system.assertEquals(false,room.readyForDelegates,'after a reset the room should be unready for delegates');

	}
}