src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Chapter_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chapter Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Graduated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate that a student (or former student) has graduated from high school.</description>
        <inlineHelpText>Used to indicate that a student (or former student) has graduated from high school.</inlineHelpText>
        <label>Graduated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>High_School_Graduation_Year__c</fullName>
        <label>High School Graduation Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_Role__c</fullName>
        <inlineHelpText>JSA Advisor = Designated Teacher/Advisor
JSA Affiliate = Other Chaperone</inlineHelpText>
        <label>JSA Role</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Affairs Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Interested Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Member_Status__c</fullName>
        <label>Member Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non-member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax-paid Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Use this record type for current high school students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/myJSAchapterController.cls
global with sharing class myJSAchapterController {

    public Contact contact {get; set;}
    
    public string studentType {get;set;}
    
    public Boolean showEvents {get;set;}

    public void initPage() {
        Id contactId = [select ContactId from User where Id = :UserInfo.getUserId()].ContactId;
        contact = [select High_School__c, High_School__r.Name, JSA_Role__c from Contact where Id = :contactId];
        string studType = ApexPages.currentPage().getParameters().get('studentType');
        if(string.isempty(studType)) {
            studentType = 'nongraduated';
        }
        else {
            studentType = studType;
        }
        showEvents = portalServices.showEvents();
    }

    public List<Contact> roster {
        get {
            List<Contact> contacts =
                [select Id, Name, Email, High_School_Graduation_Year__c
                 from Contact
                 where // Id != :contact.Id
                 High_School__c = :contact.High_School__c
                 and JSA_Role__c in ('Student', 'Chapter President', 'Chapter Officer' ,'JSA Advisor', 'JSA Affiliate')];
            return contacts;
        }
        
        private set;
    }
    
    @remoteAction
    global static List<Contact> findStudents(String schoolId, String studentType, String userId){

        Contact [] students = new Contact[]{};
        String contactId = [select ContactId from User where id =: userId].ContactId;
        
        if(studentType == 'all'){
            students = [select Id, Name, Email, High_School_Graduation_Year__c, Graduated__c, Member_Status__c, JSA_Role__c
                        from Contact 
                        where High_School__c =: schoolId
                        and JSA_Role__c in ('Student', 'Chapter President', 'Chapter Officer' ,'JSA Advisor', 'JSA Affiliate')
                        // and Id !=: contactId
                        order by LastName asc
            ];
        }else if(studentType== 'graduated'){
            students = [select Id, Name, Email, High_School_Graduation_Year__c, Graduated__c, Member_Status__c, JSA_Role__c
                        from Contact 
                        where High_School__c =: schoolId
                        and JSA_Role__c in ('Student', 'Chapter President', 'Chapter Officer' ,'JSA Advisor', 'JSA Affiliate')
                        and Graduated__c = true
                        // and Id !=: contactId
                        order by LastName asc
            ];
        }else if(studentType== 'nongraduated'){
            students = [select Id, Name, Email, High_School_Graduation_Year__c, Graduated__c, Member_Status__c, JSA_Role__c
                        from Contact 
                        where High_School__c =: schoolId
                        and JSA_Role__c in ('Student', 'Chapter President', 'Chapter Officer' ,'JSA Advisor', 'JSA Affiliate')
                        and Graduated__c = false
                        // and Id !=: contactId
                        order by LastName asc
            ];
        }else if(studentType== 'taxpaidmembers'){
            students = [select Id, Name, Email, High_School_Graduation_Year__c, Graduated__c, Member_Status__c, JSA_Role__c
                        from Contact 
                        where High_School__c =: schoolId
                        and JSA_Role__c in ('Student', 'Chapter President', 'Chapter Officer' ,'JSA Advisor', 'JSA Affiliate')
                        and Member_Status__c = 'Tax-paid Member'
                        // and Id !=: contactId
                        order by LastName asc
            ];
        }
        return students;
    }
    
    @remoteAction
    global static String declareStudentMembers(String[] studentIds, String userId){
        String JSARole = [Select Contact.JSA_Role__c from User where id=: userId].Contact.JSA_Role__c;
        if(new Set<String>{'Chapter President','JSA Advisor', 'JSA Affiliate'}.contains(JSARole)){
            String status = 'ok';
            Contact[] gradStudents = new Contact[]{};
            system.debug(studentIds);
            for(String studentId :studentIds){
                system.debug('studentId:' + studentId);
                gradStudents.add(New Contact(Id=studentId, Chapter_Member__c=true, Member_Status__c = 'Tax-paid Member'));
            }
            try{
                update gradStudents;
            }catch(Exception e){
                status = e.getMessage();
            }
            return status;
        }else{
            return 'You are not authorized to declare members.';
        }
    }
    
    @remoteAction
    global static String graduateStudents(String[] studentIds, String userId){
        String JSARole = [Select Contact.JSA_Role__c from User where id=: userId].Contact.JSA_Role__c;
        if(new Set<String>{'Chapter President','JSA Advisor', 'JSA Affiliate'}.contains(JSARole)){
            String status = 'ok';
            Contact[] gradStudents = new Contact[]{};
            system.debug(studentIds);
            for(String studentId :studentIds){
                system.debug('studentId:' + studentId);
                gradStudents.add(New Contact(Id=studentId, Graduated__c=true));
            }
            try{
                update gradStudents;
            }catch(Exception e){
                status = e.getMessage();
            }
            return status;
        }else{
            return 'You are not authorized to graduate students';
        }
    }
    
    public Boolean inflateTest() {

        Integer j = 0;

        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;
        j++;

        return true;
        
    }

}



/*
My Chapter is a list of Contacts related to the logged in users High_School__c. 
 
DISPLAY LOGIC
 
Do not display contacts where Contact.JSA_Role__c = NULL, Chapter Affairs Agent, Administrator, Academic Counselor or JSA Interested Party
 
Display students = Contact.JSA_Role__c = Student, Chapter President, Chapter Officer
 
Display teachers and teacher adivsors = JSA Advisor, JSA Affiliate
 
FILTERS
 
Non-Graduated = Contact.Graduated__c = False
 
Graduated = Contact.Graduated__c = True
 
MARK AS GRADUATED
 
Action only available to Chapter President and Teachers (Contact.JSA_Role__c = Chapter President, JSA Advisor or JSA Affiliate)
 
When a user is selected and the Mark as Graduated link is clicked, set Contact.Graduated__c = true
*/