src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_Role__c</fullName>
        <inlineHelpText>JSA Advisor = Designated Teacher/Advisor
JSA Affiliate = Other Chaperone</inlineHelpText>
        <label>JSA Role</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Affairs Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Interested Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Member_Status__c</fullName>
        <label>Member Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non-member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax-paid Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Use this record type for current high school students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/myJSAchapterControllerTest.cls
@isTest
public with sharing class myJSAchapterControllerTest
{
	static Contact testContact;
	static Account testAccount;
	static High_School__c testHs;
	static list<Contact> testHsRoster;
	
	static User portalUser;
	
	static final integer ROSTER_SIZE = 4;
	
	static void setup()
	{
		
		
		
		testAccount = testUtils.createAccounts(1,'hsAcc','OH-616')[0];
		insert testAccount;
		
		testHs = testUtils.createHighSchool('supertown', testAccount);
		insert testHs;
		
		testHsRoster = testUtils.createContacts(ROSTER_SIZE, 'bort', testAccount.id);
		
		for(contact c: testHsRoster)
		{
			// c.member_status__c = 'tax-paid member';
			c.JSA_Role__c = 'Student';
			c.High_School__c = testHs.id;
		}
		
		insert testHsRoster;
		testContact = testHsRoster[ROSTER_SIZE-1];
		// testHsRoster.remove(ROSTER_SIZE-1);
		
		portalUser = testUtils.createPortalUser('chapsuperbort@bort.com.bort', testContact.id);
		
		system.runAs(testUtils.sysadmin)
		{
			insert portalUser;
		}
	}
	
	@future
	private static void insertPortalUser(){
		
	}
	
	static testMethod void testGetRoster()
	{
		setup();
		myJSAchapterController cont = new myJSAchapterController();
		list<Contact> queriedRoster;
		
		test.startTest();
			system.runAs(portalUser)
			{
				cont.initPage();
				//force the query to happen while runnign as the test user
				queriedRoster = cont.roster;
			}
		test.stopTest();
			Set<Id> testIds= new Map<Id,Contact>(testHsRoster).keySet();
			
			for(contact c: queriedRoster)
			{
				system.assert(testIds.contains(c.id),'every contact in the roster should be found');
				// testIds.remove(c.id);
			}
			
			system.assertEquals(testHsRoster.size(),queriedRoster.size(),'all the contacts should have been found');
		
	}

	static testMethod void testInflate() {

		myJSAchapterController cont = new myJSAchapterController();

		Test.startTest();

		Boolean result = cont.inflateTest();
		System.assert(result);

		Test.stopTest();
		
	}
}