src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_Role__c</fullName>
        <inlineHelpText>JSA Advisor = Designated Teacher/Advisor
JSA Affiliate = Other Chaperone</inlineHelpText>
        <label>JSA Role</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Affairs Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Interested Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Schools</relationshipLabel>
        <relationshipName>R00N40000001qFBVEA2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assign_Room__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Individual has either paid (if there is a charge), or we have received a purchase order.</inlineHelpText>
        <label>Assign Room?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Convention__c</fullName>
        <label>Convention Location</label>
        <picklist>
            <picklistValues>
                <fullName>Northern California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern California - Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern California - Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific Northwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Texas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ohio River Valley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midwest</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Chapter or other group that the individual registration is associated with.</description>
        <inlineHelpText>Chapter or other group that the individual registration is associated with.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Individual Registrants</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_Role__c</fullName>
        <formula>CASE( Primary_Contact__r.JSA_Role__c , 
&quot;Chapter President&quot;, &quot;Chapter President&quot;, 
&quot;Student&quot;, &quot;Student&quot;,
&quot;Chapter Officer&quot;, &quot;Chapter Officer&quot;,
&quot;JSA Advisor&quot;, &quot;JSA Advisor&quot;,
&quot;JSA Affiliate&quot;, &quot;JSA Affiliate&quot;,
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JSA Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Male_Female__c</fullName>
        <inlineHelpText>This field is pre-populated based on information in the Personal Data section.  Select the appropriate room type.</inlineHelpText>
        <label>Female/Male Room</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private or Adult w/ Spouse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Permission_Form_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the parental permission form been received?</description>
        <label>Permission Form Received?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The contact record for the student or other primary contact related to the opportunity.  In the case of summer registrations through the portal, this will always be the student contact.</inlineHelpText>
        <label>Primary Contact Link</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Summer Program Applications</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ocHigh_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>High School Chapter that is sending a delegation (applies only to group opportunities).</inlineHelpText>
        <label>Host Chapter</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Overnight Conventions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ChapterConventionRegistration</fullName>
        <active>true</active>
        <businessProcess>Overnight Conventions</businessProcess>
        <description>Use this record type for schools that are coming to overnight conventions</description>
        <label>Chapter Convention Registration</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual_Convention_Registration</fullName>
        <active>true</active>
        <businessProcess>Overnight Conventions</businessProcess>
        <description>Use this record type for individuals registering for a convention (even as part of a group)</description>
        <label>Individual Convention Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/extGroupRegistration.cls
public with sharing class extGroupRegistration {
	//public Opportunity group_opp {get;set;}
	public List<Opportunity> lstRegs {get;set;}
	public String strName {get;set;}
	 
    public extGroupRegistration(ApexPages.StandardController controller) {
		//Opportunity group_opp = new Opportunity();//(Opportunity)controller.getRecord();
		
		if ((Opportunity)controller.getRecord() != null){
			Opportunity group_opp = (Opportunity)controller.getRecord(); //[Select Id, Name from Opportunity where Id = : (Opportunity)controller.getRecord().Id];
			group_opp = [Select Id, Name from Opportunity where Id = : group_opp.Id];
			if (group_opp.Id != null){
				lstRegs = [Select Id, Name, Primary_Contact__r.Name, JSA_Role__c, Assign_Room__c, Male_Female__c, Permission_Form_Received__c
					from Opportunity where Group__c =: group_opp.Id order by Primary_Contact__r.LastName, Primary_Contact__r.FirstName];
				strName = group_opp.Name;
			}
		} else { 
			//group_opp = new Opportunity();
			lstRegs = new List<Opportunity>(); 
		}
    }
    
    //Everything below is to test the code
    
    static Contact testConGen(Id idGroup, String strFirst, String strLast){
    	Contact c = new Contact(
    		FirstName = strFirst,
    		LastName = strLast,
    		AccountId = idGroup
    	);
    	
    	insert c;
    	return c;
    }//end testConGen
    
    static Opportunity testRegGen(Id idCon, Date dte, String strGen, Id idGroup, Id idRT,  String strPref, Integer intPref){
    	Opportunity o = new Opportunity(
    		Convention__c = 'Northeast', 
    		CloseDate = dte, 
    		Male_Female__c = strGen, 
    		Group__c = idGroup,
    		RecordTypeId = idRT,
    		Primary_Contact__c = idCon,
    		StageName = 'Interested',
    		Name = 'Reg'
    		);
    
    	insert o;
    

    	return o;
    }
	
	static testMethod void testPageActions() {
		Date dteCon = System.today().addDays(90);
    	Account a = new Account(
    		Name = 'Nonnewaug',
    		BillingStreet = 'Street',
    		BillingState = 'Connecticut',
    		BillingPostalCode = '06751',
    		BillingCity = 'Woodbury'
    	);
    	insert a;
    	
    	High_School__c h = new High_School__c(
            Name = 'Jessie Test HS', 
            Account__c = a.Id);
        insert h;
        
        //Get record type Ids
        Id idRTReg = [Select Id from RecordType where DeveloperName = 'Individual_Convention_Registration'][0].Id;
    	Id idRTCon = [Select Id from RecordType where DeveloperName = 'ChapterConventionRegistration'][0].Id;
    	
    	//Create Group opportunity
		Opportunity oCon = new Opportunity(
    		Convention__c = 'Northeast', 
    		CloseDate = dteCon, 
    		ocHigh_School__c = h.Id,
    		RecordTypeId = idRTCon,
    		StageName = 'Interested',
    		Name = 'Group'
    		);
    	
    	insert oCon;
    	
    	//Test to load page with a group with no registrations
    	ApexPages.StandardController stdCon = new ApexPages.StandardController(oCon);
    	extGroupRegistration ext = new extGroupRegistration(stdCon);
    	
    	//Create a registration
    	Contact c1 = testConGen(a.Id, 'Rainbow', 'Paper');
    	Opportunity r1 = testRegGen(c1.Id, dteCon, 'Female', oCon.Id, idRTReg,  '', 1);
    	
    	//Test page with group with registration
		stdCon = new ApexPages.StandardController(oCon);
		ext = new extGroupRegistration(stdCon);
	}
}