src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSA_Role__c</fullName>
        <inlineHelpText>JSA Advisor = Designated Teacher/Advisor
JSA Affiliate = Other Chaperone</inlineHelpText>
        <label>JSA Role</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter Affairs Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSA Interested Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Member_Status__c</fullName>
        <label>Member Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non-member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax-paid Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Use this record type for current high school students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MyJSAprofileControllerTest.cls
@isTest
public with sharing class MyJSAprofileControllerTest 
{
	static Contact testContact;
	static Account testAccount;
	static High_School__c testHs;
	
	static User portalUser;
	static final string HS_STATE = 'Texas';
	
	static void setup()
	{
		testAccount = testUtils.createAccounts(1,'hsAcc','OH-616')[0];
		testAccount.BillingState = HS_STATE;
		insert testAccount;
		
		testHs = testUtils.createHighSchool('supertown', testAccount);
		insert testHs;
		
		testContact = testUtils.createContacts(1, 'bort', testAccount.id)[0];
		
		testContact.member_status__c = 'tax-paid member';
		testContact.JSA_Role__c = 'Student';
		testContact.High_School__c = testHs.id;
		insert testContact;
		
		portalUser = testUtils.createPortalUser('superbort@bort.com.bort', testContact.id);
		
		system.runAs(testUtils.sysadmin)
		{
			insert portalUser;
		}
	}
	
	static testMethod void testInitPage()
	{
		setup();
		myJSAProfileController testCont = new myJSAProfilecontroller();
		
		test.startTest();
			system.runAs(portalUser)
			{
				testCont.initPage();
			}
		test.stopTest();
		
		system.assertEquals(testContact.id,testCont.contact.id,'the correct contact should be found');
		system.assertEquals(HS_STATE,testCont.highSchoolState,'the high schools state should be found');
		system.assertEquals(1,testCont.highSchoolStateOptions.size(),'there should be only one high school state option');
		system.assertEquals(HS_STATE,testCont.highSchoolStateOptions[0].getValue(),'the high school state option should be that of the test high school');
		
		//system.assertNotEquals(null,testCont.roleOptions,'the static options lists should be created');
		system.assertNotEquals(null,testCont.genderOptions,'the static options lists should be created');
		//system.assertNotEquals(null,testCont.countryOptions,'the static options lists should be created');
		//system.assertNotEquals(null,testCont.stateProvinceOptions,'the static options lists should be created');
	}
}