src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Are you a student, teacher or chaperon?</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Alum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HS Educator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>High_School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select your school from those within the ZIP code (see left). If your school is not shown, change the ZIP to 00000 and select &quot;Other&quot;.</description>
        <inlineHelpText>Search for your high school in this field. If your school is not listed, please type and select &quot;Not Listed&quot;</inlineHelpText>
        <label>High School</label>
        <referenceTo>High_School__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Status__c</fullName>
        <label>Member Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non-member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax-paid Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Use this record type for current high school students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/High_School__c.object
<CustomObject>
    <label>High School</label>
    <nameField>
        <label>High School</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>Used for summer program leads, and other new students expressing interest in JSA programs</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that user selected &quot;I agree&quot; to the Terms and Conditions.</description>
        <label>Terms and Conditions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ocStudent_Delegation_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Chapter President, or other student leader of the delegation.</inlineHelpText>
        <label>Student Delegation Leader</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conventions Led by this Student</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ocTeacher_Advisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The primary Teacher/Advisor attending the convention with the delegation. If the attending chaperon is not in the list, contact the nearest JSA office to have your chaperon added to the list.</inlineHelpText>
        <label>Primary Attending Teacher or Chaperon</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conventions Led by this Teacher/Advisor</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/jsaPortalEventControllerTest.cls
@isTest
public with sharing class jsaPortalEventControllerTest 
{
	public static Opportunity testOp;
	public static Account testAcc;
	public static High_School__c testHs;
	
	public static jsaPortalEventController testController;
	
	public static void setup()
	{
		testOp = testUtils.createOpportunities(1, 'testName', 'Application Started', Date.today())[0];
		testAcc = testUtils.createAccounts(1, 'mmm', 'zz')[0];
		
		insert testAcc;
		
		testHs = testUtils.createHighSchool('superSchool', testAcc);
		
		insert testHs;
		
		testOp.AccountId = testAcc.id;
		
		insert testOp;
	}
	
	public static jsaPortalEventController createController(Id opId)
	{
		ApexPages.currentPage().getParameters().put(jsaPortalEventController.ID_PARAM, testOp.id);
		return new jsaPortalEventController();		
	}
	
	public static testMethod void testConstruction()
	{
		setup();
		test.startTest();
			testController = createController(testOp.id);
		test.stopTest();
		
		system.assertEquals(testOp.id, testController.op.id,'the same opportunity should be quieried');
	
		system.assertEquals(false,testController.TandC,'the tems should not be accepted yet');
		system.assertEquals(null,testController.leadDelegateId,'no lead delegate should be selected');
		system.assertEquals(null,testController.advisorId,'no advisor should be selected');
		system.assertEquals(testOp.name,testController.opName,'the correct name should be found');
		system.assertEquals(null,testController.totalAmount,'since no products have been made the total amount should be null');
		system.assertNotEquals(null,testController.orderNumber,'an order number should be present');
		system.assertEquals(false,testController.submissionApproved,'submission should not be approved');
		system.assertEquals(false,testController.submitted,'should not be submitted');
		system.assertEquals(false,testController.leadershipSelected,'leadership should not be selected');
		system.assertEquals(0,testController.tabState,'the tab state should be initialized');
	}
	
	public static testMethod void testGoTos()
	{
		setup();
		testController = createController(testOp.id);
		
		test.startTest();
			testController.goToOverview();
			integer overState = testController.tabState;
			
			testController.goToTandC();
			integer tcState = testController.tabState;
			
			testController.goToProducts();
			integer prodState = testController.tabState;
			
			testController.goToRooms();
			integer roomState = testController.tabState;
			
			testController.goToInvoice();
			integer invState = testController.tabState;
		test.stopTest();
		
		system.assertEquals(0,overState,'the overview state should be correct');
		system.assertEquals('overview',testController.tabNames[overState],'the overview name should be correct');
			
		system.assertEquals(1,tcState,'the terms and conditions state should be correct');
		system.assertEquals('TandC',testController.tabNames[tcState],'the terms and conditions name should be correct');
			
		system.assertEquals(2,prodState,'the product state should be correct');
		system.assertEquals('delegates',testController.tabNames[prodState],'the delegates name should be correct');
		
		system.assertEquals(3,roomState,'the rooms state should be correct');
		system.assertEquals('rooms',testController.tabNames[roomState],'the rooms name should be correct');
		
		system.assertEquals(4,invState,'the inventory state should be correct');
		system.assertEquals('invoice',testController.tabNames[invState],'the inventory name should be correct');
	}
	
	public static testMethod void testupdateOp()
	{
		setup();
		testController = createController(testOp.id);
		final string NEW_NAME = 'NEW_NAME';
		
		test.startTest();
			testController.op.Name = NEW_NAME;
			testController.updateOp();
		test.stopTest();

		system.assert(!apexPages.hasMessages(),'there should be no error messages');		
		
		Opportunity requeriedOp = [SELECT Id,Name FROM Opportunity WHERE Id = :testOp.id];
		system.assertEquals(NEW_NAME,requeriedOp.name,'the name update should have occured');
		
	}
	
	public static testMethod void testAcceptTandC()
	{
		setup();
		testController = createController(testOp.id);
		
		test.startTest();
			testController.acceptTandC();
		test.stopTest();
		
		Opportunity requeriedOp = [SELECT Id,Terms_and_Conditions__c FROM Opportunity WHERE Id = :testOp.id];
		system.assertEquals(true,requeriedOp.Terms_and_Conditions__c,'the terms should have been accepted');
	}
	
	public static testMethod void testSetDelegateAndChaparone()
	{
		setup();

		List<Contact> contacts = testUtils.createContacts(2, 'bort', testAcc.id);
		
		for(Contact c: contacts)
		{
			c.high_school__c = 	testHs.id;
			c.Member_Status__c = 'tax-paid member';
		}
		
		Contact leadDelegate = contacts[0];
		Contact chaperone = contacts[1];
		
		leadDelegate.category__c = 'Student';
		chaperone.category__c = 'Alum';
		
		insert contacts;
		
		testController = createController(testOp.id);
		
		//plug in the high school
		testController.hs = testHs;
		
		test.startTest();
			testController.selectChapterDelegate.selectedId = leadDelegate.id;
			testController.selectChaperone.selectedId = chaperone.id;
			testController.setDelegateAndChaparone();
		test.stopTest();
		
		Opportunity requeried = [SELECT Id, ocTeacher_Advisor__c,ocStudent_Delegation_Leader__c FROM Opportunity WHERE Id = :testController.op.id];
		
		system.assertEquals(leadDelegate.id,requeried.ocStudent_Delegation_Leader__c,'the primary contact should be saved correctly');
		system.assertEquals(chaperone.id,requeried.ocTeacher_Advisor__c,'the advisor should be saved correctly');
		
		system.assertEquals(true,testController.leadershipSelected,'the leadership should be selected');
		system.assertEquals(1,testController.tabState,'the tab state should advance');
		
	}
	
	public static testMethod void testAddPackagesForParticipatingMembers()
	{

	}

	public static testMethod void testSubmitOpp()
	{

	}

	public static testMethod void testInflate() {

		setup();
		testController = createController(testOp.id);

		Test.startTest();

			Boolean result = testController.inflateTest();

		Test.stopTest();

		System.assert(result);

	}

}